name: Hello World

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  hello:
    runs-on: windows-latest

    steps:
      - name: Hello step
        run: echo "Hello World"
