name: Run tests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  hello:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.1
      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: npx jest
